### ISSUE TITLE
Zitieren von Büchern mit Autor und Herausgeber (z. B. historische Werke)

### ISSUE THREAD

**Issue by janbaumanninfoclio** [infoclio-ch/csl-style#2]
Ich habe eine Anfrage bekommen, ob es eine Möglichkeit gibt, Bücher zu zitieren, die sowohl einen Autor als auch einen Herausgeber haben (ist z. B. oft bei historischen Werken der Fall). Mit dem Zitierstil "Theologisches Seminar St. Chrischona" würde das z. B. so aussehen:
**Philo von Alexandria**: Die Werke in deutscher Übersetzung, hg. v. **Heinemann**, Isaak u. a., Bd. 1, Berlin<sup>2</sup> 1962.
[theologisches-seminar-st-chrischona.csl.zip](https://github.com/user-attachments/files/15574299/theologisches-seminar-st-chrischona.csl.zip)

Wäre es möglich unseren Zitierstil so zu erweitern, dass wenn ein (oder mehrere) Herausgeber neben dem Autor erfasst werden, diese ebenfalls im Zitat ausgegeben werden? Z. B. so:
Philo von Alexandria: Die Werke in deutscher Übersetzung, Bd. 1, hg. v. Heinemann, Isaak; Adler, Maximilian; Theiler, Willy u. a., Berlin 1962<sup>2</sup>.
<img width="333" alt="Bildschirmfoto 2024-06-05 um 08 52 34" src="https://github.com/nchachereau/csl-style-for-infoclio-ch/assets/77060611/d06a1b90-d953-48f8-ab02-8c099becbb97">

**Comment by nchachereau** [comment]
Ja, das ist sicher möglich, eigentlich erstaunlich, dass wir das nicht schon haben!

**Comment by janbaumanninfoclio** [comment]
Beispiel: https://www.zotero.org/groups/5273577/anleitung_infoclio.ch_zitierstil/items/K77ILYLR

**Comment by nchachereau** [comment]
Danke für das Beispiel! Ich wollte jetzt die Tests schreiben, habe aber dann gemerkt, dass wir nicht definiert haben, wie das Format genau aussehen soll.

Im Beispiel in diesem Issue hast du zuerst geschrieben: 
> Philo von Alexandria: Die Werke in deutscher Übersetzung, hg. v. Heinemann, Isaak u. a., Bd. 1, Berlin 1962.

Also zuerst Herausgeber, dann Band. In unserer gemeinsamen Bibliothek lautet der Vorschlag aber:
> Philo von Alexandria: Die Werke in deutscher Übersetzung, Bd. 1, hg. v. Heinemann, Isaak; Adler, Maximilian; Theiler, Willy u. a., Berlin 1962<sup>2</sup>.

Also zuerst Band, dann Herausgeber. Ich glaube aber, es wäre besser, den/die Herausgeber sofort nach dem Titel anzugeben (also wie im ersten Beispiel).

Für den französischsprachigen Stil könnte das dann so aussehen:
> Philo von Alexandria, <i>Die Werke in deutscher Übersetzung</i>, éd. par Heinemann Isaak, Adler Maximilian, Theiler Willy et al., vol. 1, 2<sup>e</sup> édition, Berlin, De Gruyter, 1962.

Was meinst du?

**Comment by nchachereau** [comment]
Danke! Letzte Frage, und dann wäre es bereit: **hg. v.** oder **hg. von**?

**Comment by janbaumanninfoclio** [comment]
Ich würde **hg. v.** vorziehen
