### ISSUE TITLE
Angabe der Übersetzer

### ISSUE THREAD

**Issue by nchachereau** [infoclio-ch/csl-style#3]
Jetzt dass wir Herausgeber angeben (#2), wollen wir nach demselben Modell die Angabe der Übersetzer:innen ins Zitierformat aufnehmen?

> Bonneuil, Christophe; Fressoz, Jean-Baptiste: The shock of the Anthropocene: the Earth, history, and us, **übers. v. Fernbach, David,** London 2016.

> Bonneuil Christophe et Fressoz Jean-Baptiste, <i>The shock of the Anthropocene: the Earth, history, and us</i>, **trad. par Fernbach David**, London, Verso, 2016.

(Wenn ja, sieht CSL auch vor, dass Herausgeber und Übersetzer zusammengenommen werden, wenn es sich um denselben Namen handelt; das hiesse dann **hg. & übers. v.** bzw. **éd. et trad. par**.)

Was denkst du, @janbaumanninfoclio ?

**Comment by janbaumanninfoclio** [comment]
Hallo Nicolas

Ja, ich finde das eine gute Idee. Du kannst das gerne so umsetzten.

Vielen Dank, liebe Grüsse
Jan



Jan Baumann
infoclio.ch <http://infoclio.ch/>
Gutenbergstrasse 37
3011 Bern
Tel: +41 31 311 75 72
***@***.*** ***@***.***>

infoclio.ch <https://www.infoclio.ch/> auf Facebook <https://www.facebook.com/infoclio.ch>, Twitter <https://twitter.com/infoclio>, Mastodon ***@***.***>
